/*
R.002665

----------

Name: Checking for mismatched itypes
Created by: Heather Braum

----------

Group: Administrative Reports
     Fix Items-admin

Created on: 2016-02-10 21:23:36
Modified on: 2016-02-10 22:18:56
Date last run: 2023-10-23 16:44:10

----------

Public: 0
Expiry: 0

----------

includes lots of common sets; may have to remove to check for these.... 

----------
*/



SELECT  CONCAT('',biblionumber,'') AS bibnumber, GROUP_CONCAT(DISTINCT itype) 
FROM items 
WHERE biblionumber NOT IN ('551728','636389','521345','682294','682294','573870','572720','568972','566864','304288','297976','577265','')
GROUP BY biblionumber 
HAVING 
count(itemnumber) &gt; '1' AND
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'AUDIOBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MAGAZINE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MUSIC' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'REFERENCE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'GAME' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'KITS' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'COMPUTER' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'ILL' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,NEWBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWBOOK,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,NEWMEDIA' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWMEDIA,MEDIA' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'AUDIOBOOK,NEWAUDIO' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWAUDIO,AUDIOBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MAGAZINE,NEWMAG' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWMAG,MAGAZINE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'REFERENCE,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,REFERENCE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MUSIC,AUDIOBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'AUDIOBOOK,MUSIC' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'AUDIOBOOK,FLPLAYAWAY' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,KITS' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'KITS,BOOK'  AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'AUDIOBOOK,KITS' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'KITS,AUDIOBOOK'  AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,LOCALHOLD2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LOCALHOLD2,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,LOCALHOLD2,NEWBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,LOCALHOLD2,NEWBOOK,WALKIN2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,WALKIN2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN2,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN,REFERENCE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'REFERENCE,WALKIN' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,LOCALHOLD1,NEWMEDIA,WALKIN1' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,LOCALHOLD1,NEWMEDIA' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,LOCALHOLD1,WALKIN1' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,LOCALHOLD1,WALKIN1,NEWMEDIA' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,LOCALHOLD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LOCALHOLD,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'AUDIOBOOK,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,AUDIOBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'AUDIOBOOK,LOCALHOLD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LOCALHOLD,AUDIOBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,NEWBOOK,LOCALHOLD2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,NEWBOOK,LOCALHOLD2,WALKIN2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,NEWBOOK,REFERENCE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,NEWBOOK,WALKIN2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,NEWBOOK,WALKIN2,LOCALHOLD2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,REFERENCE,WALKIN' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,WALKIN' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,REFERENCE,NEWBOOK' AND
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'BOOK,WALKIN,REFERENCE' AND
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'EQUIPMENT' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'FLPLAYAWAY' AND
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'FLPLAYAWAY,AUDIOBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'FLPLAYAWQAY,LOCALHOLD' AND
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'EQUIPMENT,WALKIN' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'EQUIPMENT,KITS' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'EQUIPMENT,COMPUTER' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'FLPLAYAWAY,LOCALHOLD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'COMPUTER,EQUIPMENT' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'COMPUTER,WALKIN,EQUIPMENT' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'KITS,EQUIPMENT' AND
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LAUNCHPAD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LOCALHOLD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LAUNCHPAD,LOCALHOLD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LOCALHOLD,EQUIPMENT' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LOCALHOLD,LAUNCHPAD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'LOCALHOLD2,NEWBOOK,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,LOCALHOLD1' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,NEWMEDIA,LOCALHOLD1' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,WALKIN1,NEWMEDIA' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MEDIA,WALKIN1,NEWMEDIA,LOCALHOLD1' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MIFI' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWAUDIO' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWBOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWMAG' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWBOOK,BOOK,LOCALHOLD2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWBOOK,BOOK,REFERENCE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWBOOK,BOOK,WALKIN2' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWBOOK,REFERENCE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'NEWBOOK,REFERENCE,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'REFERENCE,BOOK,WALKIN' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'REFERENCE,MAGAZINE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN,BOOK,REFERENCE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN,LOCALHOLD' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN,REFERENCE,BOOK' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'WALKIN,MAGAZINE' AND 
GROUP_CONCAT(DISTINCT itype) &lt;&gt; 'MAGAZINE,WALKIN'
ORDER BY GROUP_CONCAT(DISTINCT itype)

























